esphome:
  name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: components

logger:
  level: DEBUG

i2c:
  - id: bus_a
    sda: 20
    scl: 21
    scan: true

bq25798:
  id: bq25798_component_1
  i2c_id: bus_a
  # iindpm: 500 # optional
  # vindpm: 4500 # optional
  # ichg: 1000 # optional
  # adc_en: true # optional
  # adc_rate: ADC_RATE_CONTINUOUS
  # adc_sample: ADC_SAMPLE_15BIT

# At least an empty "sensor" block is required to initialize the component (and make the sensor.h accessible)
sensor:

#   - platform: bq25798
#     name: "Test"
#     id: bq25798_component_1
#     on_click:
#       then:
#         - logger.log: "Clicked"
