esphome:
  name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: components

logger:
  level: DEBUG

i2c:
  - id: bus_a
    sda: 20
    scl: 21
    scan: true

bq25798:
  id: bq25798_component_1
  i2c_id: bus_a
  # address: 0x01 # optional
  iindpm: 500 # optional
  vindpm: 4500 # optional
  ichg: 1000 # optional
  adc_en: true # optional
  adc_rate: CONTINUOUS
  adc_sample: ADC_SAMPLE_15BIT

# # sensor:
# #   - platform: bq25798
# #     name: "Test"
# #     id: bq25798_component_1
# #     on_click:
# #       then:
# #         - logger.log: "Clicked"
